### ISSUE TITLE
Ending support for Carthage?

### ISSUE THREAD

**Issue by miktav** [twilio/twilio-chat-ios#24]
Hi, the update today removing support for Carthage was unexpected. This broke our build this morning and caused a bit of a scramble. Thank you for putting the support back. How are customers advised of breaking changes before they happen so they can take appropriate steps? Thanks, Mike

**Comment by Gray-Wind** [comment]
Sorry for that. We did not mean to break existing builds and CI process by any mean.

We for a long time had plans to support XCFramework. Since we for time being can only provide a binary version of the framework, it become impossible to keep support for Carthage.

We will return Carthage distribution once it would add support for binary frameworks.

For now you can use either SPM, CocoaPods or manual integration.

Feel free to ask if you have any more questions.

**Comment by miktav** [comment]
Thanks, this helps. We can make the switch, it's just not something we can do immediately. We have multiple apps dependent on this and need time to coordinate and test, etc.

**Comment by berkus** [comment]
@miktav sorry about that, it was an incorrect ad-hoc decision on our part. We will warn ahead of breaking infrastructure changes.

**Comment by Gray-Wind** [comment]
I'm going to close this ticket. If you have any questions and/or comments feel free to left them here or create a new ticket.
